export default {
  noUpcoming: "Waheguru Ji! There are no upcoming programs.",
  programLocations: {
    headquarters: "Headquarters",
    outside: "Outside",
  },
  phoneNumber: "+91-98513-92513",
  forMoreInfo: "For More Information",
  bhaiSahibName: "Bhai Sahib Bhai Sewa Singh Ji Tarmala",
  bhaiSahibTitle: "Founder",
  veerjiName: "Bhai Sahib Bhai Dalbir Singh Ji Tarmala",
  veerjiTitle: "President",
  ourCourses:
    '<span style="font-size: 1.5em">O</span>UR <span style="font-size: 1.5em">C</span>OURSES',
  oneYearCourse: "1 Year Course",
  oneYearCourseDescription:
    'Course starts from 7 April to 31 March, after obtaining the<br><span style="color: #da4f03;">Daat Of Amrit</span><br>from Guru (Panj Pyaare) on Amrit Sanchar Smagam (29-31 March)',
  fourYearCourse: "4 Year Course",
  fourYearCourseDescription:
    "Complete Divine Course<br>starts from 7 April for 4 Years.<br>Anyone can join this course from age 15-60",
  dailyClassesHeading: "Daily Classes Schedule | University Of Divine Studies",
  headingUpcoming: "Upcoming Programs",
  headingUniversity: "University of Divine Studies, Life Changes Here",
  headingWeTeach: "We Teach",
  headingExtraClasses: "Extra Learning Classes",
  headingDailyHukumnama: "Daily Hukumnama",
  headingPrograms: "Programs",
  joinClasses: "Join these classes online on Youtube & Radio",
  youtubeLink: "https://www.youtube.com/wahegurulive/live",
  headingLiveVideo: "Waheguru Live Video",
  headingLiveSchedule: "Live Schedule",
  liveRadioHTML1:'<script type="text\/javascript" src="https:\/\/hosted.muses.org\/mrp.js"><\/script><script type=\"text\/javascript\"> MRP.insert({ \'url\':\'http:\/\/cast1.asurahosting.com\/proxy\/gpmkc\/stream\', \'codec\':\'mp3\', \'volume\':100, \'autoplay\':true, \'jsevents\':true, \'buffering\':0, \'title\':\'\', \'wmode\':\'transparent\', \'skin\':\'simple-gray\', \'width\':300, \'height\':122 }); <\/script>',
  liveRadioStreamURL: 'http://cast1.asurahosting.com/proxy/gpmkc/stream',
  playPause: 'Play/Pause',
  stop: 'Stop',
  loaded: 'Loaded',
  loading: 'Loading...',
  playing:'Playing...',
  paused: 'Paused.',
  stopped: 'Stopped.',
  errored:'Error!',
  ended: 'Ended',
  init:'🙏 Press play to start.'
};
