export default {
  noUpcoming: "Waheguru Ji! There are no upcoming programs.",
  programLocations: {
    headquarters: "Headquarters",
    outside: "Outside",
  },
  phoneNumber: "+91-98513-92513",
  forMoreInfo: "For More Information",
  bhaiSahibName: "Bhai Sahib Bhai Sewa Singh Ji Tarmala",
  bhaiSahibTitle: "Founder",
  veerjiName: "Bhai Sahib Bhai Dalbir Singh Ji Tarmala",
  veerjiTitle: "President",
  ourCourses:
    '<span style="font-size: 1.5em">O</span>UR <span style="font-size: 1.5em">C</span>OURSES',
  oneYearCourse: "1 Year Course",
  oneYearCourseDescription:
    'Course starts from 7 April to 31 March, after obtaining the<br><span style="color: #da4f03;">Daat Of Amrit</span><br>from Guru (Panj Pyaare) on Amrit Sanchar Smagam (29-31 March)',
  fourYearCourse: "4 Year Course",
  fourYearCourseDescription:
    "Complete Divine Course<br>starts from 7 April for 4 Years.<br>Anyone can join this course from age 15-60",
  dailyClassesHeading: "Daily Classes Schedule | University Of Divine Studies",
  headingUpcoming: "Upcoming Programs",
  headingUniversity: "University of Divine Studies, Life Changes Here",
  headingWeTeach: "We Teach",
  headingExtraClasses: "Extra Learning Classes",
  headingDailyHukumnama: "Daily Hukumnama",
  headingPrograms: "Programs",
  joinClasses: "Join these classes online on Youtube & Radio",
  youtubeLink: "https://www.youtube.com/wahegurulive/live",
  headingLiveVideo: "Waheguru Live Video",
  headingLiveRadio: "Waheguru Live Radio",
  headingLiveSchedule: "Live Schedule",
  liveRadioHTML1:'<script type="text\/javascript" src="https:\/\/hosted.muses.org\/mrp.js"><\/script><script type=\"text\/javascript\"> MRP.insert({ \'url\':\'http:\/\/cast1.asurahosting.com\/proxy\/gpmkc\/stream\', \'codec\':\'mp3\', \'volume\':100, \'autoplay\':true, \'jsevents\':true, \'buffering\':0, \'title\':\'\', \'wmode\':\'transparent\', \'skin\':\'simple-gray\', \'width\':300, \'height\':122 }); <\/script>',
  liveRadioStreamURL: 'http://cast1.asurahosting.com/proxy/gpmkc/stream',
  playPause: 'Play/Pause',
  stop: 'Stop',
  loaded: 'Loaded',
  loading: 'Loading...',
  playing:'Playing...',
  paused: 'Paused.',
  stopped: 'Stopped.',
  errored:'Error!',
  ended: 'Ended',
  init:'🙏 Press play to start.',
  headingOurMission:'Our Mission',
  headingAboutUs:'About Us',
  ourMissionText:'To share and experience common love for the inner divine according to teachings of<br>Sahib Shri Guru Granth Sahib Ji.',
  universityTitle:"University Of Divine Studies Moga",
  bhaiSahibAbout:"Bhai Sahib was born on 10th August 1944 at village Bahuliana, Tehsil Chunni in district Lahore. He did his schooling in Abohar and then Giani in 1972 from Punjabi University, Patiala. Bhai Sewa Singh's native village is Tarmala in district Mukatsar, Punjab. In his early childhood he was inspired to imbibe Gurmat by his father S. Kundan Singh and mother Mata Ishar Kaur.<br><br>In 1978, he took Baptism \"Amrit\" at the inspiring persuasion of his close associate, Bhai Inderjit Singh Narangwal. His mother was spiritually inclined towards Naam Simran. The holy company of his mother and many other saintly souls laid the solid foundation of spirituality in his early life. With Akal Purkh's grace and through Naam Simran and Sabad-Surat practice, he became enlightened. He preaches and teaches union with Waheguru on the basis of the inspired and the revealed word of Gurbani. Preaching pure Gurmat, he explains techniques that lead to an ultimate union with Waheguru through Naam Simran. His wife Bibi Daljit Kaur is the source of inspiration behind this mission. Many other members of Bhai Sahib's family have been contributing towards the fulfillment of this noble mission.<br><br>By keeping such as great mission in mind and with the association of inspired Gurmukhs, Bhai Sahib established Sarab Sukh Charitable trust in 2005. Construction of Institute of Divine studies, Gurdwara Prabh Milne Ka Chao was started in Moga.<br><br>One year and four year courses were started in 2007. The purpose of the courses is to teach the students how to live their life by following Gurmat. By the grace of God and under the direction of a great quote from Gurbani \“Recognise whole human race as of one caste,\” rays of enlightenment are spreading to each and every corner of the world by this Institute.",
  veerjiAbout:"With the grace of Waheguru, Bhai Sahib Bhai Sewa Singh Ji Tarmala established Gurdwara Prabh Milne Ka Chao (University Of Divine Studies) in 2007. In which the idea of selfless service, Naam Simran and Akath Katha continues after Bhai Sahib Bhai Sewa Singh Tarmala merged back in truth on December 06 2012, under the able guidance of their successor, beloved Gurmukh Bhai Sahib Bhai Dalbir Singh Tarmala who is purifying the atmosphere and human hearts continuously with the sounds(sacred hymns) of Gurbani Guru.<br><br>While proceeding on the path of devotion, he has experienced the supernatural bliss of union with Waheguru by the grace of Waheguru after receiving entire techniques, methods and secrets of Gurbani from family heritage. According to the sacred Gurbani quote \“Recognise whole human race as of one caste,\” Bhai Sahib Bhai Dalbir Singh Tarmala is devoted to propagating Gurmat all the time inspiring the worldly beings to follow Naam Simran and spiritual pathway. He motivates every individual to walk on the path as explained in Gurbani Guru, enlightening the right path for them.<br><br>Avoiding the queries related to the materialistic world Bhai Sahib explains all the obstacles that are yet to come on the path of devotion, as explained in Gurbani Guru, to spiritual seekers in the congregation.<br><br>Fortunate are the ones who had a chance to meet Gurmukhs like Bhai Sahib Bhai Sewa Singh Tarmala. Needless to say such opportunities arise only by the grace of Waheguru. Even today one can feel the same spiritual warmth after listening to Gurbani Guru\’s explanations by Bhai Sahib\’s appointed successor, his own image, respected Bhai Dalbir Singh Tarmala. Altogether, his great personality creates a determination in the mind of spiritual seekers to get united with the universal master (Prabh Milne Ka Chao)",
  headingGallery:"Gallery",
  videoGalleryLink:"https://www.youtube.com/c/Wahegurulive/playlists",
  videoGallery:"Video Gallery",
  audioGallery:"Audio Gallery",
  audioGalleryLink: "https://archive.org/details/@gurdwara_prabh_milne_ka_chao",
  photoGallery:"Photo Gallery",
  photoGalleryLink: "https://www.facebook.com/wahegurulive/photos?tab=albums",
  instagramGallery:"Instagram Gallery",
  instagramGalleryLink: "https://www.instagram.com/gpmkc.moga",
  whatsappLink:"https://wa.me/919851392513",
  headingStore: "Store",
  orderOnWhatsApp:"Order on Whatsapp",
  orderOnWhatsAppLink:"https://wa.me/c/919851392513",
  headingContactUs: "Contact Us",
  contactInfo:"Gurdwara Prabh Milne Ka Chao, Rauli Road, Near Bughipura Chownk, Moga, Punjab 142001<br><br>gpmkc.moga@gmail.com<br><br>+91 98513-92513<br>+91 81950-13223",
  readDailyHukumnama: "Read Daily Hukumnama",
  followUs: "Follow Us",
  websiteUrl: "https://wahegurulive.com/",
  youtubeUrl: "https://www.youtube.com/c/Wahegurulive",
  instagramUrl: "https://www.instagram.com/gpmkc.moga/",
  twitterUrl: "https://twitter.com/wahegurulive",
  facebookUrl: "http://www.facebook.com/wahegurulive",
  soundCloudUrl: "https://soundcloud.com/wahegurulive",
  getInTouch: "Get in Touch",
  gurdwaraNameFooter: "Gurdwara Prabh Milne Ka Chao",
  universityNameFooter: "University of Divine Studies",
  gurdwaraInfoFooter: "Near Bughipura Chownk, Rauli Road, Moga(Punjab)<br>Contact No: +91 98513-92513, 8195013223<br>Email: gpmkc.moga@gmail.com",
  quickContact: "Quick Contact",
  subject: "Subject",
  message: "Message",
  email: "Email",
  copyrightFooter: "(c) Copyright Sarab Sukh Charitable Trust Moga , All rights reserved.",
  website: "Website",
  youtube: "YouTube",
  facebook: "Facebook",
  instagram: "Instagram",
  soundCloud: "Soundcloud",
  twitter: "Twitter",
  internetArchive:"Internet Archive",
  whatsapp:"WahtsApp",
  required:"Required",
  checkForm: "Please check all entries.",
  gpmkcEmail:"gpmkc.moga@gmail.com",
  location: "Location",
  s404:"Error 404: Page not found!",
  WaheguruJi: "Waheguru Ji",
  pageNotFound:"Page not found!",
  anErrorOccurred: "An error occurred!",
  pleaseFindAllPages: "Please find all the pages below ji",
  dailyHukumnama: "Daily Hukumnama",
  home:"Home",
  about:"About",
  live:"Live",
  liveRadio: "Live Radio",
  liveVideo: "Live Video",
  gallery: "Gallery",
  store:"Store",
  contact:"Contact",
  programs: "Programs",
  waheguruLive: "Waheguru Live",
  titleExtension: " - Gurdwara Prabh Milne Ka Chao Moga - Bhai Sewa Singh Ji Tarmala",
  subscribeMessage: "Get daily Hukumnama alerts on Website",
  subscribe: "Subscribe",
  unsubscribe: "Unsubscribe",
};
